// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXiEFqAj0nRnO_bDtYaUfz7DBfzCk8XY8',
    appId: '1:834853361688:web:02ed0ba87c7123e9754b6d',
    messagingSenderId: '834853361688',
    projectId: 'who-am-i-d2854',
    authDomain: 'who-am-i-d2854.firebaseapp.com',
    storageBucket: 'who-am-i-d2854.appspot.com',
    measurementId: 'G-S22TX379XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBaN9ui_8mArZRjY7xySOi68VxkvuxSg',
    appId: '1:834853361688:android:9a18f6944b099109754b6d',
    messagingSenderId: '834853361688',
    projectId: 'who-am-i-d2854',
    storageBucket: 'who-am-i-d2854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_2ujh8A2_gKBUbKZaCvcKV9w4Udi-9rc',
    appId: '1:834853361688:ios:94f619a8989598ac754b6d',
    messagingSenderId: '834853361688',
    projectId: 'who-am-i-d2854',
    storageBucket: 'who-am-i-d2854.appspot.com',
    iosClientId: '834853361688-3tplegpkaaaahjrt9i9rgmabr86cl3ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.resume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_2ujh8A2_gKBUbKZaCvcKV9w4Udi-9rc',
    appId: '1:834853361688:ios:94f619a8989598ac754b6d',
    messagingSenderId: '834853361688',
    projectId: 'who-am-i-d2854',
    storageBucket: 'who-am-i-d2854.appspot.com',
    iosClientId: '834853361688-3tplegpkaaaahjrt9i9rgmabr86cl3ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.resume',
  );
}
